apiVersion: apps/v1
kind: Deployment
metadata:
  name: cneura-llm
  namespace: cneura-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cneura-llm
  template:
    metadata:
      labels:
        app: cneura-llm
    spec:
      serviceAccountName: vault-loader-sa
      volumes:
        - name: secret-volume
          emptyDir: {}
      initContainers:
        - name: secretvault-loader
          image: shehandezen/cneura-vault-agent:latest
          env:
            - name: SECRET_IDS
              value: "cneura-core:mongo-uri=MONGO_URI,cneura-core:llm-log-db=DB_NAME,cneura-core:llm-priv-key=PRIV_KEY,cneura-core:llm-security-group=SECURITY_GROUP,cneura-core:cneura-auth-host=AUTH_HOST,cneura-core:cneura-auth-port=AUTH_PORT,cneura-core:google-gemini-key=GEMINI_API_KEY,cneura-core:google-gemini-key=GOOGLE_API_KEY"
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-master-key
                  key: master.key
            - name: OUTPUT_PATH
              value: "/secrets/.env"
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
      containers:
        - name: llm
          image: shehandezen/cneura-llm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
---
apiVersion: v1
kind: Service
metadata:
  name: cneura-llm-svc
  namespace: cneura-core
spec:
  selector:
    app: cneura-llm
  ports:
    - port: 50052
      targetPort: 50052
      protocol: TCP
  type: ClusterIP
