apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-manager-sa
  namespace: cneura-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resource-manager-role
  namespace: cneura-core
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-manager-rolebinding
  namespace: cneura-core
subjects:
  - kind: ServiceAccount
    name: resource-manager-sa
    namespace: cneura-core
roleRef:
  kind: Role
  name: resource-manager-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cneura-resource-manager
  namespace: cneura-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cneura-resource-manager
  template:
    metadata:
      labels:
        app: cneura-resource-manager
    spec:
      serviceAccountName: resource-manager-sa
      volumes:
        - name: secret-volume
          emptyDir: {}
      initContainers:
        - name: secretvault-loader
          image: shehandezen/cneura-vault-agent:latest
          env:
            - name: SECRET_IDS
              value: "cneura-core:mongo-uri=MONGO_URI,cneura-core:resource-manager-priv-key=PRIV_KEY,cneura-core:resource-manager-security-group=SECURITY_GROUP,cneura-core:core-namespace=NAMESPACE,cneura-core:resource-manager-app-db=APP_DB,cneura-core:resource-manager-job-db=JOB_DB,cneura-core:cneura-auth-host=AUTH_HOST,cneura-core:cneura-auth-port=AUTH_PORT"
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-master-key
                  key: master.key
            - name: OUTPUT_PATH
              value: "/secrets/.env"
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
      containers:
        - name: resource-manager
          image: shehandezen/cneura-resource-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50058
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
          livenessProbe:
            tcpSocket:
              port: 50058
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 50058
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cneura-resource-manager-svc
  namespace: cneura-core
spec:
  selector:
    app: cneura-resource-manager
  ports:
    - port: 50058
      targetPort: 50058
      protocol: TCP
  type: ClusterIP
