apiVersion: apps/v1
kind: Deployment
metadata:
  name: cneura-sandbox
  namespace: cneura-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cneura-sandbox
  template:
    metadata:
      labels:
        app: cneura-sandbox
    spec:
      serviceAccountName: vault-loader-sa
      volumes:
        - name: secret-volume
          emptyDir: {}
      initContainers:
        - name: secretvault-loader
          image: shehandezen/cneura-vault-agent:latest
          env:
            - name: SECRET_IDS
              value: "cneura-core:mongo-uri=MONGO_URI,cneura-core:sandbox-priv-key=PRIV_KEY,cneura-core:sandbox-security-group=SECURITY_GROUP,cneura-core:cneura-auth-host=AUTH_HOST,cneura-core:cneura-auth-port=AUTH_PORT"
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-master-key
                  key: master.key
            - name: OUTPUT_PATH
              value: "/secrets/.env"
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
      containers:
        - name: sandbox
          image: shehandezen/cneura-sandbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50053
          livenessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cneura-sandbox-svc
  namespace: cneura-core
spec:
  selector:
    app: cneura-sandbox
  ports:
    - port: 50053
      targetPort: 50053
      protocol: TCP
  type: ClusterIP
