apiVersion: v1
kind: Namespace
metadata:
  name: cneura-core
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-loader-sa
  namespace: cneura-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-loader-role
  namespace: cneura-core
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-loader-rb
  namespace: cneura-core
subjects:
  - kind: ServiceAccount
    name: vault-loader-sa
    namespace: cneura-core
roleRef:
  kind: Role
  name: vault-loader-role
  apiGroup: rbac.authorization.k8s.io
